baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Glen's Blog"
theme = "binario"
sectionPagesMenu = 'main'
[Params]
  dateFormat = "January 02, 2006" # Change the format of dates
#  comments = true # Enable comments for all site pages

[Params.Social]
  email = "gwg313@pm.me"
  github = "gwg313"

[Author] # Used in authorbox
  name = "Glen"

[Params.Entry]
  meta = ["date", "categories", "tags"] # Enable meta fields in given order
#  toc = true # Enable Table of Contents
  tocOpen = true # Open Table of Contents block. Optional
